name: Docker Build & Test
permissions:
    contents: read
    pull-requests: write

on:
    push:
        branches: [main, stable]
    pull_request:
        branches: [main, stable]

jobs:
    docker-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11", "3.12"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker image with Python ${{ matrix.python-version }}
              run: |
                  DOCKER_BUILDKIT=1 docker build -f docker/Dockerfile \
                    --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                    --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
                    -t rag-colls:${{ matrix.python-version }} .
